### ISSUE TITLE
Webhook fail on internal_api/webhook

### ISSUE THREAD

**Issue by pini-gh** [tmate-io/tmate-websocket#4]
Hi,

I'm aware that you recommend `tilt`, but my server runs several services already using `ansible` + `docker-compose`, and I'd like it to host a `tmate` service as well.

I'm almost there: `tmate-ssh-server` works. But not `tmate-websocket` where the docker log reports this error on new sessions:
```
token=[CGM5...] id=9b211210-79b0-11eb-98df-0242ac120007 [info] Session started stoken=CGM5... stoken_ro=ro-bKmp... ssh_only=false foreground=false named=false
[warn] Webhook fail on internal_api/webhook - Retrying event :session_register (:nxdomain)
```
And the web session URL returns `404` with this text: `:(`.

I see no error message in the `tmate-ssh-server` docker log.

Here is my `docker-compose` configuration:
```
version: "3.5"

services:
  tmate-ssh-server:
    image: tmate/tmate-ssh-server:latest
    container_name: tmate-ssh-server
    restart: unless-stopped
    cap_add:
    - SYS_ADMIN
    ports:
    - "2200:22"
    environment:
      HAS_WEBSOCKET: 1
      WEBSOCKET_HOSTNAME: tmate-websocket
      SSH_KEYS_PATH: "/etc/tmate-keys"
      SSH_HOSTNAME: tmate.example.com
      SSH_PORT_LISTEN: 22
      SSH_PORT_ADVERTISE: 2200
    volumes:
    - ssh-keys:/etc/tmate-keys
    - unix-sockets:/tmp/tmate/sessions
    networks:
      bridge:

  tmate-websocket:
    image: tmate/tmate-websocket:latest
    container_name: tmate-websocket
    restart: unless-stopped
    environment:
      ERL_NODE_NAME: tmate.example.com
      ERL_COOKIE: myerlcookie
      # Not sure at all about this one
      WEBSOCKET_BASE_URL: http://tmate-websocket:4001/
      USER_FACING_BASE_URL: https://tmate.example.com/
      DAEMON_HMAC_KEY: myhmackey
      INTERNAL_API_AUTH_TOKEN: myinternaltoken
    volumes:
    - unix-sockets:/tmp/tmate/sessions
    networks:
      bridge:

volumes:
  ssh-keys:
  unix-sockets:

networks:
  bridge:
```

Note: I had to tweak the `tmate-ssh-server`'s entrypoint to pass the websocket container's host name (`WEBSOCKET_HOSTNAME`) to the daemon, because it was hardcoded to `localhost`.

**Comment by pini-gh** [comment]
I eventually managed to have the suite up and running with successful web session. Here is the fixed docker-compose file:
```
version: "3.5"

services:
  tmate-ssh-server:
    image: tmate/tmate-ssh-server:latest
    container_name: tmate-ssh-server
    restart: unless-stopped
    cap_add:
    - SYS_ADMIN
    ports:
    - "2200:22"
    environment:
      HAS_WEBSOCKET: 1
      WEBSOCKET_HOSTNAME: tmate-websocket
      SSH_KEYS_PATH: "/etc/tmate-keys"
      SSH_HOSTNAME: tmate.example.com
      SSH_PORT_LISTEN: 22
      SSH_PORT_ADVERTISE: 2200
    volumes:
    - ssh-keys:/etc/tmate-keys
    - unix-sockets:/tmp/tmate/sessions
    networks:
      bridge:

  tmate-websocket:
    image: tmate/tmate-websocket:latest
    container_name: tmate-websocket
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: tmate-ws.example.com
      VIRTUAL_PORT: 4001
      CERT_NAME: example.com
      WEBSOCKET_BASE_URL: wss://tmate-ws.example.com/
      MASTER_BASE_URL: https://tmate.example.com/
      USER_FACING_BASE_URL: https://tmate.example.com/
      ERL_NODE_NAME: tmate.example.com
      ERL_COOKIE: myerlcookie
      DAEMON_HMAC_KEY: mydaemonhmackey
      INTERNAL_API_AUTH_TOKEN: myinternalapiauthtoken
    volumes:
    - unix-sockets:/tmp/tmate/sessions
    networks:
      bridge:

  tmate-master:
    image: tmate/tmate-master:latest
    container_name: tmate-master
    # https://github.com/tmate-io/tmate-master/issues/13#issuecomment-787470427
    hostname: tmate-1
    domainname: example.com
    restart: unless-stopped
    expose:
    - 4000
    environment:
      VIRTUAL_HOST: tmate.example.com
      VIRTUAL_PORT: 4000
      CERT_NAME: example.com
      MASTER_BASE_URL: https://tmate.example.com/
      ERL_COOKIE: myerlcookie
      # Must match <hostname>.<domainname>
      ERL_NODE_NAME: tmate-1.example.com
      # ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
      SECRET_KEY_BASE: 0123456789abcdefghijklmnopqrstuvwxyz=0123456789abcdefghijklmnopqrstuvwxyz
      INTERNAL_API_AUTH_TOKEN: myinternalapiauthtoken
      PG_URI: postgres://tmate:postgrespassword@tmate-db:5432/tmate
      # Muste be >= 2
      PG_POOLSIZE: 5
    networks:
      bridge:
      internal:

  tmate-db:
    image: postgres:12-alpine
    container_name: tmate-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tmate
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tmate
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
      internal:

volumes:
  ssh-keys:
  unix-sockets:
  pgdata:

networks:
  bridge:
  internal:
    internal: true
```
Note: the variables `VIRTUAL_HOST`, `VIRTUAL_PORT` and `CERT_NAME` are related to the reverse proxy [`nginx-proxy`](https://github.com/nginx-proxy/nginx-proxy).
